### ISSUE TITLE
ZeroTier having issues reconnecting after Windows sleep/hibernate

### ISSUE THREAD

**Issue by ChlodAlejandro** [zerotier/ZeroTierOne#1958]
May be related to #1921.

## Description

ZeroTier One is having issues reconnecting to networks following a system suspend (sleep or hibernate). When the system is first restored, attempting to connect to any machine on a ZeroTier network does not work. Pinging the machine results in a timeout (console output below).
```
Pinging machine.hostname [10.1.1.1] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 10.1.1.1:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```
At this point, ZeroTier One is still responsive. `zerotier-cli info` gives out `200 info [NODE_ID redacted] 1.10.6 ONLINE`, as expected. `zerotier-cli listnetworks` gives out a list of networks, as expected. `zerotier-cli dump` can be written.

Attempting to restart the `ZeroTierOneService` service through the Services menu results in timeouts, but the service does stop after some time. Any request on the service (start/stop/restart) will time out following suspension. Following a service restart (if it does go through), the issue persists. The "Network Connections" menu on the Control Panel indicate that all ZeroTier virtual network adapters are unplugged, some coming online for a brief moment (without the machines on the network actually being accessible).

Any request on the ZeroTier service at this point fail:
```
Error connecting to the ZeroTier service: timed out

Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.
```

Sometimes it fixes itself after 10-20 minutes. Sometimes a restart is required to fix the issue.

## Reproduction
1. Install ZeroTier (connect to a network, all that jazz)
2. Put the device on sleep or hibernate
3. Wake the device from sleep or hibernate
4. ZeroTier connections don't seem to work. **Issue begins.**

## Additional information
* ZeroTier One 1.10.6 on Windows (x86/x64)
* Microsoft Windows 11, Version 22H2 (OS Build 22621.1485)
* This issue doesn't seem to occur on ZeroTier One 1.8, my previous version prior to upgrading (which was when this issue began occurring).
* This seems reminiscent of safing/portmaster#1041, another issue where connections get blocked post-wake (but, in this case, without the CPU usage spike).

**Comment by grandted** [comment]
I'm using ZeroTier 1.10.1 where this issue almost doesn't exist. Then I'm still trying every new version that comes out and I can confirm that 10.2 - 10.6 all have this issue so every time I go back to 10.1.

**Comment by Da1Liu** [comment]
> I'm using ZeroTier 1.10.1 where this issue almost doesn't exist. Then I'm still trying every new version that comes out and I can confirm that 10.2 - 10.6 all have this issue so every time I go back to 10.1.

Thx，it helps a lot!

**Comment by lflare** [comment]
Can confirm that @grandted's tip on using 1.10.1 has resolved my issue of having to wait around for ZeroTier to reconnect after waking my Windows. Looking at the code diff, perhaps it has something to do with the multipath improvement from 1.10.1 to 1.10.2? 

https://github.com/zerotier/ZeroTierOne/compare/1.10.1...1.10.2

**Comment by KweezyCode** [comment]
![image](https://github.com/zerotier/ZeroTierOne/assets/36813920/8c4816f6-b072-4e4a-b38a-a1d1842d968f)
![image](https://github.com/zerotier/ZeroTierOne/assets/36813920/5af75a46-b918-43e7-b07e-2a571c12e1d0)
still same issue

**Comment by warren-ru** [comment]
I also face this issue

**Comment by gbdrbob** [comment]
also seeing this issue with 1.10.6 on Windows 11.

**Comment by Hamza141** [comment]
I've also been seeing this issue on the last several releases. Gonna revert to 1.10.1 as suggested by [grandted](https://github.com/grandted)

**Comment by laduke** [comment]
I'm having trouble reproducing this. Anyone other hints would be helpful. 
Do you use default route? or anything not-default on the network or on the client? How long do you need to sleep for? 
Are you on a consumer router, or at work behind a corporate thing?
etc..

**Comment by gbdrbob** [comment]
> I'm having trouble reproducing this. Anyone other hints would be helpful. 
> Do you use default route? or anything not-default on the network or on the client? 

Almost everything is set to defaults, I have a single extra route set up in zerotier so I can access hosts on a local subnet behind zerotier running on a router.

>How long do you need to sleep for? 

Not sure, I usually notice the problem when waking up the computer in the morning, so several hours.

>Are you on a consumer router, or at work behind a corporate thing? etc.. 

The PC I experience this problem on is behind a consumer ISP provided router, I believe the router is Linux based.

>Do you have ipv6 connectivity to the internet?

Yes.

**Comment by lflare** [comment]
> Do you use default route? or anything not-default on the network or on the client? 

I use a default route, as well as a few more local network routes that do not overlap with the local network route of the client.

> How long do you need to sleep for?

No specific timing, but I've noted that a few hours is enough to cause this bug from occurring on my end. Notably, the bug only exists from 1.10.2 and up, thus all my clients have been pinned to 1.10.1 while this bug is still active, as having to wait around more than 5 minutes upon waking gets tiring.

> Are you on a consumer router, or at work behind a corporate thing?

No, I've experienced this on all kinds of networks

> Do you have ipv6 connectivity to the internet?

No

**Comment by laduke** [comment]
This should be fixed in dev, lflare. New release "soon"

**Comment by lflare** [comment]
> This should be fixed in dev, lflare. New release "soon" Thanks for everyone's help in reproducing and debugging.

Awesome, apologies for the really late follow-up from myself, even though you were asking for hints 3 weeks ago 😅

**Comment by laduke** [comment]
Let us know if 1.12.1 didn't fix this. Thanks!

**Comment by gbdrbob** [comment]
I'm still having an issue with this, I just checked (1.12.1) whilst it seems faster than before it still took 4 minutes after waking from sleep before my desktop PC was able to connect to a zerotier host not on the local network. The status in the tray app showed as "connected" throughout.

**Comment by laduke** [comment]
hey thanks for writing. there's 1.12.2 now. it may be a little better than 1.12.1.

**Comment by kleuter** [comment]
Still experiencing connection problems after wake up in 1.12.2 on Windows 11 unfortunately

**Comment by stuckj** [comment]
I see this with 1.12.2 in both Linux and Windows as well. It's about 3-4 minutes before there is connectivity between peers though it shows as online.

**Comment by joamla96** [comment]
Just found this issue as well through google.
Im having the same, with 1.14 on Windows 11. Seems to be a couple of minutes at least before peers actually gets connected.

I am currently on a dual stack network, but my home network is ipv4 only.

**Comment by kleuter** [comment]
still the same issue on Windows 10/11, I wonder why @laduke closed this

**Comment by diegomesata** [comment]
Hello, its very strange, on Windows server 2016 after a reboot the I network interface doesn't work, I have to open the tray icon menu, click in the interface ip, it looks like a Power shell windows appears and the interface start working.

![image](https://github.com/user-attachments/assets/94588446-0ca8-4e28-9c53-e5bffe60a922)

![image](https://github.com/user-attachments/assets/387e8c8a-3cff-48c8-9746-5e2dc791d1dd)
