### ISSUE TITLE
Push DNS server to devices

### ISSUE THREAD

**Issue by StrikerTwo** [zerotier/ZeroTierOne#632]
I have several "road warrior" laptops connected with ZeroTier to our internal network. They are members of our AD domain. For this to work, they need a Domain Controller as DNS server on the ZT interface.
At the moment we have to set that manually after installing ZT and connecting it to the ZT network.

Problem is that if we forget that step, it works for a time (because login credentials are cached etc.) and then stops working when both the user and the laptop are somewhere else.

It would be nice if we could set a list of DNS servers for a ZT network that gets pushed to the connected devices together with the (auto-)assigned IP address.

The alternative would be running our own DHCP server on every ZT network and ignoring the IP assignment features that ZT provides. Which would be more work for us, more error-prone and less nice to use ;)

**Comment by StrikerTwo** [comment]
I just saw #360. However, I don't see what the big problem is. We have pushed DNS servers in our PPTP, L2TP, OpenVPN and SoftEther connections for years without problems. If the VPN connection drops out, the OS uses the DNS servers on the other interface(s) like before.

Also, I don't care about resolving devices hostnames to internal ZT addresses. I just need to provide my clients with a resolver.

**Comment by adamierymenko** [comment]
This is a dupe of #322 in the sense that we eventually want to support DHCP. DHCP can do this. Security concerns apply.

**Comment by franbotha** [comment]
@StrikerTwo could you possibly assist me in how you manually did the DNS configuration on your clients please?

**Comment by StrikerTwo** [comment]
Win+X -> Network connections -> Properties of your ZT interface -> TCP/IP v4 -> Properties.

You could probably script something with netsh as well, but I had only a couple of clients.

**Comment by franbotha** [comment]
@StrikerTwo  unfortunately in my case this still does not work - and I think it is mainly because I am still not able to ping the ZT IP of my DC. I have Firewall off and AV uninstalled. Not sure if my Cyberroam firewall would be blocking this but then I should not be able to ping any of my servers - at the moment it is just the DC.

**Comment by StrikerTwo** [comment]
@franbotha Well then you have other problems than DNS ;)
Do the DCs have a route to the ZT network? My DCs have no default gateway because they don't need internet access, so I had to add a route manually.

**Comment by franbotha** [comment]
@StrikerTwo thank you for getting back to me. They do have a route to the ZT range yes:

![image](https://user-images.githubusercontent.com/36884933/38604650-4e60a52c-3d71-11e8-80b6-8e3476d6ce3e.png)

**Comment by StrikerTwo** [comment]
Ah, so the DC has a ZT interface itself.
Then I'm out of ideas. Maybe try deactivating your firewall?

**Comment by franbotha** [comment]
@StrikerTwo some feedback about this. I removed the interface and then also removed the IP that ZT reserved for my DC. I then reinstalled the interface onto the DC, removed the bridging option and assigned it a new IP. Reboot.

I could the ping the DC's ZT IP externally and internally. I then added the ZT IP of my DC into my ZT interface on my laptop and it started showing up as a domain network. Finally - I can see the DC via hostname as well and ping it both ways. I could still not reach the File Server tho, so I just added a line in my hosts file which points the File Server hostname to its ZT IP.

Just detailing it out so it might help someone else who is also having issues.

I just need to test and see how this is going to work out being onsite and offsite - for users that travel for instance. I will report back.

**Comment by franbotha** [comment]
Hi guys.

So I have tested it some more and my findings are that if the computer was in my physical network the same day or before, then it will not allow it to connect. It does not find the DNS server. However, with Bridging option on the DC and File Server enabled, the users in other branches connect perfectly fine without the manual DNS entry or changing anything in the host file.

Would I be right in saying that the issue is with the DNS and the TTL or time-out?

**Comment by StrikerTwo** [comment]
Sure, it could be a DNS caching issue. You can check on the command line with `nslookup <your.domain.local>` to see which DNS server it uses and what the result is.
