### ISSUE TITLE
Bug / Feature: MTU should default to 1280 or 1390

### ISSUE THREAD

**Issue by unquietwiki** [zerotier/ZeroTierOne#975]
* https://blog.cloudflare.com/increasing-ipv6-mtu/
* https://cloud.google.com/vpn/docs/concepts/mtu-considerations
* https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-tcpip-performance-tuning

With the default MTU of 2800 on ZeroTier interfaces; as of mid-2019, cloud-providers still have issues properly handling VPN tunnels, as well as fully supporting IPv6 traffic. Google appears to suggest using 1390 (70 less than their 1460 limit on instances); Azure and Cloudflare both use/recommend 1400. Using 1280 doesn't seem to be required in these environments at least; it might be necessary for other environments.

Alternatively, maybe there's some kind of lookup table/intelligence, that could be deployed to help users avoid connectivity issues?

**Comment by adamierymenko** [comment]
This is fixed in `dev` which is shipping shortly. The UDP MTU default is now 1432 and works fine on all these AFIAK.

**Comment by unquietwiki** [comment]
Thanks @adamierymenko for addressing this!

**Comment by alatteri** [comment]
> This is fixed in `dev` which is shipping shortly. The UDP MTU default is now 1432 and works fine on all these AFIAK.

As of 1.4.6 new networks are still defaulting to MTU 2800.

**Comment by cortices** [comment]
I'm still getting network problems from the default virtual interface MTU being 2800 that are fixed by changing to 1500.

**Comment by alatteri** [comment]
5 years later:
As of 1.16.1 new networks are still defaulting to MTU 2800. Is 1432 default still in yet to be rolled in?

**Comment by ebenali** [comment]
I get a bunch of `debug1: expecting SSH2_MSG_KEX_ECDH_REPLY` when connecting through SSH and a[ bunch of online stuff](https://unix.stackexchange.com/questions/722954/ssh-stuck-at-expecting-ssh2-msg-kex-ecdh-reply) seems to point towards MTU
